workflows:
    native-android:
        name: Native Android
        max_build_duration: 60
        environment:
           groups:
                - gcloud_credentials
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: main
                  include: true
                  source: true
        scripts:
           - name: Build debug apk
             script: ./gradlew assembleDebug
        artifacts:
            - app/build/outputs/**/*.apk
        publishing:
            scripts:
               - name: gcp instance connection and running test cases
                 script: |
                    set -ex
                    echo $JSON_KEY > ./gcloud_key_file.json
                    gcloud auth activate-service-account --key-file=gcloud_key_file.json
                    gcloud config set project $GCLOUD_PROJECT
                    #!/bin/sh
                    echo "Find build artifacts"
                    apkPath=$(find $FCI_BUILD_DIR -name "*.apk" | head -1)
                    if [ -z ${apkPath} ]; then
                        echo "No apks were found"
                        exit 1
                    else
                        gcloud beta compute ssh --ssh-flag="-T" --zone "us-central1-b" "geethukn@magnifi-mobile" -- "sudo docker exec magnifi-mobile-kvm2 /bin/bash  -c "/test.sh $apkPath $GITHUB_ACCESS_TOKEN""
                    fi
            email:
               recipients:
                   - gavisiddayyab@datatemplate.com
